server:
  port: 9090
spring:
  application:
    name: spring-boot-redis
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    redis:
      enabled: true
